#include "hc_blocks.h"

#include <string.h>

/* 순서는 hc_blocks.h enum 과 1:1 */
static const char *const NAMES[HC_B_COUNT] = {
    "minecraft:air",
    "minecraft:stone",
    "minecraft:water[level=0]",
    "minecraft:lava[level=0]",
    "minecraft:copper_ore",
    "minecraft:raw_copper_block",
    "minecraft:granite",
    "minecraft:deepslate_iron_ore",
    "minecraft:raw_iron_block",
    "minecraft:tuff",
    "minecraft:bedrock",
    "minecraft:deepslate[axis=y]",
    "minecraft:dirt",
    "minecraft:grass_block[snowy=false]",
    "minecraft:coarse_dirt",
    "minecraft:sand",
    "minecraft:sandstone",
    "minecraft:red_sand",
    "minecraft:red_sandstone",
    "minecraft:gravel",
    "minecraft:mud",
    "minecraft:mycelium[snowy=false]",
    "minecraft:podzol[snowy=false]",
    "minecraft:snow_block",
    "minecraft:powder_snow",
    "minecraft:ice",
    "minecraft:packed_ice",
    "minecraft:calcite",
    "minecraft:terracotta",
    "minecraft:white_terracotta",
    "minecraft:orange_terracotta",
    "minecraft:yellow_terracotta",
    "minecraft:brown_terracotta",
    "minecraft:red_terracotta",
    "minecraft:light_gray_terracotta",
    "minecraft:sulfur",
    "minecraft:cinnabar",
    "minecraft:andesite",
    "minecraft:diorite",
    "minecraft:clay",
    "minecraft:coal_ore",
    "minecraft:deepslate_coal_ore",
    "minecraft:iron_ore",
    "minecraft:gold_ore",
    "minecraft:deepslate_gold_ore",
    "minecraft:redstone_ore[lit=false]",
    "minecraft:deepslate_redstone_ore[lit=false]",
    "minecraft:diamond_ore",
    "minecraft:deepslate_diamond_ore",
    "minecraft:lapis_ore",
    "minecraft:deepslate_lapis_ore",
    "minecraft:deepslate_copper_ore",
    "minecraft:emerald_ore",
    "minecraft:deepslate_emerald_ore",
    "minecraft:magma_block",
    "minecraft:infested_stone",
    "minecraft:infested_deepslate[axis=y]",
    /* --- 07_features step 9 (Task 9b) — hc_blocks.h BASE 공식과 1:1.
     * 문자열은 골든 07 팔레트 직렬화와 동일 (프로퍼티 알파벳 순). */
    "minecraft:short_grass",
    "minecraft:fern",
    "minecraft:poppy",
    "minecraft:dandelion",
    "minecraft:moss_block",
    "minecraft:moss_carpet",
    "minecraft:azalea",
    "minecraft:flowering_azalea",
    "minecraft:spore_blossom",
    "minecraft:tall_grass[half=lower]",
    "minecraft:tall_grass[half=upper]",
    "minecraft:oak_log[axis=x]",
    "minecraft:oak_log[axis=y]",
    "minecraft:oak_log[axis=z]",
    "minecraft:jungle_log[axis=x]",
    "minecraft:jungle_log[axis=y]",
    "minecraft:jungle_log[axis=z]",
    "minecraft:oak_leaves[distance=1,persistent=false,waterlogged=false]",
    "minecraft:oak_leaves[distance=2,persistent=false,waterlogged=false]",
    "minecraft:oak_leaves[distance=3,persistent=false,waterlogged=false]",
    "minecraft:oak_leaves[distance=4,persistent=false,waterlogged=false]",
    "minecraft:oak_leaves[distance=5,persistent=false,waterlogged=false]",
    "minecraft:oak_leaves[distance=6,persistent=false,waterlogged=false]",
    "minecraft:oak_leaves[distance=7,persistent=false,waterlogged=false]",
    "minecraft:oak_leaves[distance=1,persistent=false,waterlogged=true]",
    "minecraft:oak_leaves[distance=2,persistent=false,waterlogged=true]",
    "minecraft:oak_leaves[distance=3,persistent=false,waterlogged=true]",
    "minecraft:oak_leaves[distance=4,persistent=false,waterlogged=true]",
    "minecraft:oak_leaves[distance=5,persistent=false,waterlogged=true]",
    "minecraft:oak_leaves[distance=6,persistent=false,waterlogged=true]",
    "minecraft:oak_leaves[distance=7,persistent=false,waterlogged=true]",
    "minecraft:jungle_leaves[distance=1,persistent=false,waterlogged=false]",
    "minecraft:jungle_leaves[distance=2,persistent=false,waterlogged=false]",
    "minecraft:jungle_leaves[distance=3,persistent=false,waterlogged=false]",
    "minecraft:jungle_leaves[distance=4,persistent=false,waterlogged=false]",
    "minecraft:jungle_leaves[distance=5,persistent=false,waterlogged=false]",
    "minecraft:jungle_leaves[distance=6,persistent=false,waterlogged=false]",
    "minecraft:jungle_leaves[distance=7,persistent=false,waterlogged=false]",
    "minecraft:jungle_leaves[distance=1,persistent=false,waterlogged=true]",
    "minecraft:jungle_leaves[distance=2,persistent=false,waterlogged=true]",
    "minecraft:jungle_leaves[distance=3,persistent=false,waterlogged=true]",
    "minecraft:jungle_leaves[distance=4,persistent=false,waterlogged=true]",
    "minecraft:jungle_leaves[distance=5,persistent=false,waterlogged=true]",
    "minecraft:jungle_leaves[distance=6,persistent=false,waterlogged=true]",
    "minecraft:jungle_leaves[distance=7,persistent=false,waterlogged=true]",
    "minecraft:vine[east=true,north=false,south=false,up=false,west=false]",
    "minecraft:vine[east=false,north=true,south=false,up=false,west=false]",
    "minecraft:vine[east=false,north=false,south=true,up=false,west=false]",
    "minecraft:vine[east=false,north=false,south=false,up=true,west=false]",
    "minecraft:vine[east=false,north=false,south=false,up=false,west=true]",
    "minecraft:cocoa[age=0,facing=north]",
    "minecraft:cocoa[age=0,facing=east]",
    "minecraft:cocoa[age=0,facing=south]",
    "minecraft:cocoa[age=0,facing=west]",
    "minecraft:cocoa[age=1,facing=north]",
    "minecraft:cocoa[age=1,facing=east]",
    "minecraft:cocoa[age=1,facing=south]",
    "minecraft:cocoa[age=1,facing=west]",
    "minecraft:cocoa[age=2,facing=north]",
    "minecraft:cocoa[age=2,facing=east]",
    "minecraft:cocoa[age=2,facing=south]",
    "minecraft:cocoa[age=2,facing=west]",
    "minecraft:bamboo[age=0,leaves=none,stage=0]",
    "minecraft:bamboo[age=0,leaves=none,stage=1]",
    "minecraft:bamboo[age=0,leaves=small,stage=0]",
    "minecraft:bamboo[age=0,leaves=small,stage=1]",
    "minecraft:bamboo[age=0,leaves=large,stage=0]",
    "minecraft:bamboo[age=0,leaves=large,stage=1]",
    "minecraft:bamboo[age=1,leaves=none,stage=0]",
    "minecraft:bamboo[age=1,leaves=none,stage=1]",
    "minecraft:bamboo[age=1,leaves=small,stage=0]",
    "minecraft:bamboo[age=1,leaves=small,stage=1]",
    "minecraft:bamboo[age=1,leaves=large,stage=0]",
    "minecraft:bamboo[age=1,leaves=large,stage=1]",
    "minecraft:cave_vines[age=0,berries=false]",
    "minecraft:cave_vines[age=1,berries=false]",
    "minecraft:cave_vines[age=2,berries=false]",
    "minecraft:cave_vines[age=3,berries=false]",
    "minecraft:cave_vines[age=4,berries=false]",
    "minecraft:cave_vines[age=5,berries=false]",
    "minecraft:cave_vines[age=6,berries=false]",
    "minecraft:cave_vines[age=7,berries=false]",
    "minecraft:cave_vines[age=8,berries=false]",
    "minecraft:cave_vines[age=9,berries=false]",
    "minecraft:cave_vines[age=10,berries=false]",
    "minecraft:cave_vines[age=11,berries=false]",
    "minecraft:cave_vines[age=12,berries=false]",
    "minecraft:cave_vines[age=13,berries=false]",
    "minecraft:cave_vines[age=14,berries=false]",
    "minecraft:cave_vines[age=15,berries=false]",
    "minecraft:cave_vines[age=16,berries=false]",
    "minecraft:cave_vines[age=17,berries=false]",
    "minecraft:cave_vines[age=18,berries=false]",
    "minecraft:cave_vines[age=19,berries=false]",
    "minecraft:cave_vines[age=20,berries=false]",
    "minecraft:cave_vines[age=21,berries=false]",
    "minecraft:cave_vines[age=22,berries=false]",
    "minecraft:cave_vines[age=23,berries=false]",
    "minecraft:cave_vines[age=24,berries=false]",
    "minecraft:cave_vines[age=25,berries=false]",
    "minecraft:cave_vines[age=0,berries=true]",
    "minecraft:cave_vines[age=1,berries=true]",
    "minecraft:cave_vines[age=2,berries=true]",
    "minecraft:cave_vines[age=3,berries=true]",
    "minecraft:cave_vines[age=4,berries=true]",
    "minecraft:cave_vines[age=5,berries=true]",
    "minecraft:cave_vines[age=6,berries=true]",
    "minecraft:cave_vines[age=7,berries=true]",
    "minecraft:cave_vines[age=8,berries=true]",
    "minecraft:cave_vines[age=9,berries=true]",
    "minecraft:cave_vines[age=10,berries=true]",
    "minecraft:cave_vines[age=11,berries=true]",
    "minecraft:cave_vines[age=12,berries=true]",
    "minecraft:cave_vines[age=13,berries=true]",
    "minecraft:cave_vines[age=14,berries=true]",
    "minecraft:cave_vines[age=15,berries=true]",
    "minecraft:cave_vines[age=16,berries=true]",
    "minecraft:cave_vines[age=17,berries=true]",
    "minecraft:cave_vines[age=18,berries=true]",
    "minecraft:cave_vines[age=19,berries=true]",
    "minecraft:cave_vines[age=20,berries=true]",
    "minecraft:cave_vines[age=21,berries=true]",
    "minecraft:cave_vines[age=22,berries=true]",
    "minecraft:cave_vines[age=23,berries=true]",
    "minecraft:cave_vines[age=24,berries=true]",
    "minecraft:cave_vines[age=25,berries=true]",
    "minecraft:cave_vines_plant[berries=false]",
    "minecraft:cave_vines_plant[berries=true]",
    "minecraft:glow_lichen[down=true,east=false,north=false,south=false,up=false,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=false,east=true,north=false,south=false,up=false,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=true,east=true,north=false,south=false,up=false,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=false,east=false,north=true,south=false,up=false,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=true,east=false,north=true,south=false,up=false,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=false,east=true,north=true,south=false,up=false,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=true,east=true,north=true,south=false,up=false,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=false,east=false,north=false,south=true,up=false,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=true,east=false,north=false,south=true,up=false,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=false,east=true,north=false,south=true,up=false,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=true,east=true,north=false,south=true,up=false,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=false,east=false,north=true,south=true,up=false,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=true,east=false,north=true,south=true,up=false,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=false,east=true,north=true,south=true,up=false,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=true,east=true,north=true,south=true,up=false,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=false,east=false,north=false,south=false,up=true,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=true,east=false,north=false,south=false,up=true,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=false,east=true,north=false,south=false,up=true,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=true,east=true,north=false,south=false,up=true,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=false,east=false,north=true,south=false,up=true,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=true,east=false,north=true,south=false,up=true,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=false,east=true,north=true,south=false,up=true,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=true,east=true,north=true,south=false,up=true,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=false,east=false,north=false,south=true,up=true,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=true,east=false,north=false,south=true,up=true,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=false,east=true,north=false,south=true,up=true,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=true,east=true,north=false,south=true,up=true,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=false,east=false,north=true,south=true,up=true,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=true,east=false,north=true,south=true,up=true,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=false,east=true,north=true,south=true,up=true,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=false]",
    "minecraft:glow_lichen[down=false,east=false,north=false,south=false,up=false,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=true,east=false,north=false,south=false,up=false,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=false,east=true,north=false,south=false,up=false,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=true,east=true,north=false,south=false,up=false,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=false,east=false,north=true,south=false,up=false,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=true,east=false,north=true,south=false,up=false,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=false,east=true,north=true,south=false,up=false,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=true,east=true,north=true,south=false,up=false,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=false,east=false,north=false,south=true,up=false,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=true,east=false,north=false,south=true,up=false,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=false,east=true,north=false,south=true,up=false,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=true,east=true,north=false,south=true,up=false,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=false,east=false,north=true,south=true,up=false,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=true,east=false,north=true,south=true,up=false,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=false,east=true,north=true,south=true,up=false,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=true,east=true,north=true,south=true,up=false,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=false,east=false,north=false,south=false,up=true,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=true,east=false,north=false,south=false,up=true,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=false,east=true,north=false,south=false,up=true,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=true,east=true,north=false,south=false,up=true,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=false,east=false,north=true,south=false,up=true,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=true,east=false,north=true,south=false,up=true,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=false,east=true,north=true,south=false,up=true,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=true,east=true,north=true,south=false,up=true,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=false,east=false,north=false,south=true,up=true,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=true,east=false,north=false,south=true,up=true,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=false,east=true,north=false,south=true,up=true,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=true,east=true,north=false,south=true,up=true,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=false,east=false,north=true,south=true,up=true,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=true,east=false,north=true,south=true,up=true,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=false,east=true,north=true,south=true,up=true,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]",
    "minecraft:glow_lichen[down=true,east=false,north=false,south=false,up=false,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=false,east=true,north=false,south=false,up=false,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=true,east=true,north=false,south=false,up=false,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=false,east=false,north=true,south=false,up=false,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=true,east=false,north=true,south=false,up=false,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=false,east=true,north=true,south=false,up=false,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=true,east=true,north=true,south=false,up=false,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=false,east=false,north=false,south=true,up=false,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=true,east=false,north=false,south=true,up=false,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=false,east=true,north=false,south=true,up=false,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=true,east=true,north=false,south=true,up=false,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=false,east=false,north=true,south=true,up=false,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=true,east=false,north=true,south=true,up=false,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=false,east=true,north=true,south=true,up=false,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=true,east=true,north=true,south=true,up=false,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=false,east=false,north=false,south=false,up=true,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=true,east=false,north=false,south=false,up=true,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=false,east=true,north=false,south=false,up=true,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=true,east=true,north=false,south=false,up=true,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=false,east=false,north=true,south=false,up=true,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=true,east=false,north=true,south=false,up=true,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=false,east=true,north=true,south=false,up=true,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=true,east=true,north=true,south=false,up=true,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=false,east=false,north=false,south=true,up=true,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=true,east=false,north=false,south=true,up=true,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=false,east=true,north=false,south=true,up=true,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=true,east=true,north=false,south=true,up=true,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=false,east=false,north=true,south=true,up=true,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=true,east=false,north=true,south=true,up=true,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=false,east=true,north=true,south=true,up=true,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=true,east=true,north=true,south=true,up=true,waterlogged=true,west=false]",
    "minecraft:glow_lichen[down=false,east=false,north=false,south=false,up=false,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=true,east=false,north=false,south=false,up=false,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=false,east=true,north=false,south=false,up=false,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=true,east=true,north=false,south=false,up=false,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=false,east=false,north=true,south=false,up=false,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=true,east=false,north=true,south=false,up=false,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=false,east=true,north=true,south=false,up=false,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=true,east=true,north=true,south=false,up=false,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=false,east=false,north=false,south=true,up=false,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=true,east=false,north=false,south=true,up=false,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=false,east=true,north=false,south=true,up=false,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=true,east=true,north=false,south=true,up=false,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=false,east=false,north=true,south=true,up=false,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=true,east=false,north=true,south=true,up=false,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=false,east=true,north=true,south=true,up=false,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=true,east=true,north=true,south=true,up=false,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=false,east=false,north=false,south=false,up=true,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=true,east=false,north=false,south=false,up=true,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=false,east=true,north=false,south=false,up=true,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=true,east=true,north=false,south=false,up=true,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=false,east=false,north=true,south=false,up=true,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=true,east=false,north=true,south=false,up=true,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=false,east=true,north=true,south=false,up=true,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=true,east=true,north=true,south=false,up=true,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=false,east=false,north=false,south=true,up=true,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=true,east=false,north=false,south=true,up=true,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=false,east=true,north=false,south=true,up=true,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=true,east=true,north=false,south=true,up=true,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=false,east=false,north=true,south=true,up=true,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=true,east=false,north=true,south=true,up=true,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=false,east=true,north=true,south=true,up=true,waterlogged=true,west=true]",
    "minecraft:glow_lichen[down=true,east=true,north=true,south=true,up=true,waterlogged=true,west=true]",
    "minecraft:big_dripleaf[facing=north,tilt=none,waterlogged=false]",
    "minecraft:big_dripleaf[facing=north,tilt=none,waterlogged=true]",
    "minecraft:big_dripleaf[facing=east,tilt=none,waterlogged=false]",
    "minecraft:big_dripleaf[facing=east,tilt=none,waterlogged=true]",
    "minecraft:big_dripleaf[facing=south,tilt=none,waterlogged=false]",
    "minecraft:big_dripleaf[facing=south,tilt=none,waterlogged=true]",
    "minecraft:big_dripleaf[facing=west,tilt=none,waterlogged=false]",
    "minecraft:big_dripleaf[facing=west,tilt=none,waterlogged=true]",
    "minecraft:big_dripleaf_stem[facing=north,waterlogged=false]",
    "minecraft:big_dripleaf_stem[facing=north,waterlogged=true]",
    "minecraft:big_dripleaf_stem[facing=east,waterlogged=false]",
    "minecraft:big_dripleaf_stem[facing=east,waterlogged=true]",
    "minecraft:big_dripleaf_stem[facing=south,waterlogged=false]",
    "minecraft:big_dripleaf_stem[facing=south,waterlogged=true]",
    "minecraft:big_dripleaf_stem[facing=west,waterlogged=false]",
    "minecraft:big_dripleaf_stem[facing=west,waterlogged=true]",
    "minecraft:small_dripleaf[facing=north,half=lower,waterlogged=false]",
    "minecraft:small_dripleaf[facing=north,half=lower,waterlogged=true]",
    "minecraft:small_dripleaf[facing=north,half=upper,waterlogged=false]",
    "minecraft:small_dripleaf[facing=north,half=upper,waterlogged=true]",
    "minecraft:small_dripleaf[facing=east,half=lower,waterlogged=false]",
    "minecraft:small_dripleaf[facing=east,half=lower,waterlogged=true]",
    "minecraft:small_dripleaf[facing=east,half=upper,waterlogged=false]",
    "minecraft:small_dripleaf[facing=east,half=upper,waterlogged=true]",
    "minecraft:small_dripleaf[facing=south,half=lower,waterlogged=false]",
    "minecraft:small_dripleaf[facing=south,half=lower,waterlogged=true]",
    "minecraft:small_dripleaf[facing=south,half=upper,waterlogged=false]",
    "minecraft:small_dripleaf[facing=south,half=upper,waterlogged=true]",
    "minecraft:small_dripleaf[facing=west,half=lower,waterlogged=false]",
    "minecraft:small_dripleaf[facing=west,half=lower,waterlogged=true]",
    "minecraft:small_dripleaf[facing=west,half=upper,waterlogged=false]",
    "minecraft:small_dripleaf[facing=west,half=upper,waterlogged=true]",
    "minecraft:red_mushroom",
    "minecraft:brown_mushroom",
    /* --- Task 10: 링 프리픽스 본문 블록 (hc_blocks.h BASE 공식과 1:1) --- */
    "minecraft:rooted_dirt",
    "minecraft:hanging_roots[waterlogged=false]",
    "minecraft:hanging_roots[waterlogged=true]",
    "minecraft:seagrass",
    "minecraft:tall_seagrass[half=lower]",
    "minecraft:tall_seagrass[half=upper]",
    "minecraft:melon",
    "minecraft:smooth_basalt",
    "minecraft:amethyst_block",
    "minecraft:budding_amethyst",
    "minecraft:azalea_leaves[distance=1,persistent=false,waterlogged=false]",
    "minecraft:azalea_leaves[distance=2,persistent=false,waterlogged=false]",
    "minecraft:azalea_leaves[distance=3,persistent=false,waterlogged=false]",
    "minecraft:azalea_leaves[distance=4,persistent=false,waterlogged=false]",
    "minecraft:azalea_leaves[distance=5,persistent=false,waterlogged=false]",
    "minecraft:azalea_leaves[distance=6,persistent=false,waterlogged=false]",
    "minecraft:azalea_leaves[distance=7,persistent=false,waterlogged=false]",
    "minecraft:azalea_leaves[distance=1,persistent=false,waterlogged=true]",
    "minecraft:azalea_leaves[distance=2,persistent=false,waterlogged=true]",
    "minecraft:azalea_leaves[distance=3,persistent=false,waterlogged=true]",
    "minecraft:azalea_leaves[distance=4,persistent=false,waterlogged=true]",
    "minecraft:azalea_leaves[distance=5,persistent=false,waterlogged=true]",
    "minecraft:azalea_leaves[distance=6,persistent=false,waterlogged=true]",
    "minecraft:azalea_leaves[distance=7,persistent=false,waterlogged=true]",
    "minecraft:flowering_azalea_leaves[distance=1,persistent=false,waterlogged=false]",
    "minecraft:flowering_azalea_leaves[distance=2,persistent=false,waterlogged=false]",
    "minecraft:flowering_azalea_leaves[distance=3,persistent=false,waterlogged=false]",
    "minecraft:flowering_azalea_leaves[distance=4,persistent=false,waterlogged=false]",
    "minecraft:flowering_azalea_leaves[distance=5,persistent=false,waterlogged=false]",
    "minecraft:flowering_azalea_leaves[distance=6,persistent=false,waterlogged=false]",
    "minecraft:flowering_azalea_leaves[distance=7,persistent=false,waterlogged=false]",
    "minecraft:flowering_azalea_leaves[distance=1,persistent=false,waterlogged=true]",
    "minecraft:flowering_azalea_leaves[distance=2,persistent=false,waterlogged=true]",
    "minecraft:flowering_azalea_leaves[distance=3,persistent=false,waterlogged=true]",
    "minecraft:flowering_azalea_leaves[distance=4,persistent=false,waterlogged=true]",
    "minecraft:flowering_azalea_leaves[distance=5,persistent=false,waterlogged=true]",
    "minecraft:flowering_azalea_leaves[distance=6,persistent=false,waterlogged=true]",
    "minecraft:flowering_azalea_leaves[distance=7,persistent=false,waterlogged=true]",
    "minecraft:small_amethyst_bud[facing=down,waterlogged=false]",
    "minecraft:small_amethyst_bud[facing=down,waterlogged=true]",
    "minecraft:small_amethyst_bud[facing=up,waterlogged=false]",
    "minecraft:small_amethyst_bud[facing=up,waterlogged=true]",
    "minecraft:small_amethyst_bud[facing=north,waterlogged=false]",
    "minecraft:small_amethyst_bud[facing=north,waterlogged=true]",
    "minecraft:small_amethyst_bud[facing=south,waterlogged=false]",
    "minecraft:small_amethyst_bud[facing=south,waterlogged=true]",
    "minecraft:small_amethyst_bud[facing=west,waterlogged=false]",
    "minecraft:small_amethyst_bud[facing=west,waterlogged=true]",
    "minecraft:small_amethyst_bud[facing=east,waterlogged=false]",
    "minecraft:small_amethyst_bud[facing=east,waterlogged=true]",
    "minecraft:medium_amethyst_bud[facing=down,waterlogged=false]",
    "minecraft:medium_amethyst_bud[facing=down,waterlogged=true]",
    "minecraft:medium_amethyst_bud[facing=up,waterlogged=false]",
    "minecraft:medium_amethyst_bud[facing=up,waterlogged=true]",
    "minecraft:medium_amethyst_bud[facing=north,waterlogged=false]",
    "minecraft:medium_amethyst_bud[facing=north,waterlogged=true]",
    "minecraft:medium_amethyst_bud[facing=south,waterlogged=false]",
    "minecraft:medium_amethyst_bud[facing=south,waterlogged=true]",
    "minecraft:medium_amethyst_bud[facing=west,waterlogged=false]",
    "minecraft:medium_amethyst_bud[facing=west,waterlogged=true]",
    "minecraft:medium_amethyst_bud[facing=east,waterlogged=false]",
    "minecraft:medium_amethyst_bud[facing=east,waterlogged=true]",
    "minecraft:large_amethyst_bud[facing=down,waterlogged=false]",
    "minecraft:large_amethyst_bud[facing=down,waterlogged=true]",
    "minecraft:large_amethyst_bud[facing=up,waterlogged=false]",
    "minecraft:large_amethyst_bud[facing=up,waterlogged=true]",
    "minecraft:large_amethyst_bud[facing=north,waterlogged=false]",
    "minecraft:large_amethyst_bud[facing=north,waterlogged=true]",
    "minecraft:large_amethyst_bud[facing=south,waterlogged=false]",
    "minecraft:large_amethyst_bud[facing=south,waterlogged=true]",
    "minecraft:large_amethyst_bud[facing=west,waterlogged=false]",
    "minecraft:large_amethyst_bud[facing=west,waterlogged=true]",
    "minecraft:large_amethyst_bud[facing=east,waterlogged=false]",
    "minecraft:large_amethyst_bud[facing=east,waterlogged=true]",
    "minecraft:amethyst_cluster[facing=down,waterlogged=false]",
    "minecraft:amethyst_cluster[facing=down,waterlogged=true]",
    "minecraft:amethyst_cluster[facing=up,waterlogged=false]",
    "minecraft:amethyst_cluster[facing=up,waterlogged=true]",
    "minecraft:amethyst_cluster[facing=north,waterlogged=false]",
    "minecraft:amethyst_cluster[facing=north,waterlogged=true]",
    "minecraft:amethyst_cluster[facing=south,waterlogged=false]",
    "minecraft:amethyst_cluster[facing=south,waterlogged=true]",
    "minecraft:amethyst_cluster[facing=west,waterlogged=false]",
    "minecraft:amethyst_cluster[facing=west,waterlogged=true]",
    "minecraft:amethyst_cluster[facing=east,waterlogged=false]",
    "minecraft:amethyst_cluster[facing=east,waterlogged=true]",
    "minecraft:cave_air",
    /* monster_room (R5d) */
    "minecraft:cobblestone",
    "minecraft:mossy_cobblestone",
    "minecraft:spawner",
    "minecraft:chest[facing=north,type=single,waterlogged=false]",
    "minecraft:chest[facing=south,type=single,waterlogged=false]",
    "minecraft:chest[facing=west,type=single,waterlogged=false]",
    "minecraft:chest[facing=east,type=single,waterlogged=false]",
    /* 밴드 링 초목 (hc_blocks.h 주석 참조) */
    "minecraft:bush",
    "minecraft:pumpkin",
    "minecraft:sugar_cane[age=0]",
    "minecraft:firefly_bush",
    "minecraft:kelp[age=20]",
    "minecraft:kelp[age=21]",
    "minecraft:kelp[age=22]",
    "minecraft:kelp[age=23]",
    "minecraft:kelp_plant",
    /* Task 13 postProcess 산물 (hc_blocks.h 주석 참조) */
    "minecraft:water[level=1]",
    "minecraft:water[level=2]",
    "minecraft:water[level=3]",
    "minecraft:water[level=4]",
    "minecraft:water[level=5]",
    "minecraft:water[level=6]",
    "minecraft:water[level=7]",
    "minecraft:water[level=8]",
    "minecraft:water[level=9]",
    "minecraft:water[level=10]",
    "minecraft:water[level=11]",
    "minecraft:water[level=12]",
    "minecraft:water[level=13]",
    "minecraft:water[level=14]",
    "minecraft:water[level=15]",
    "minecraft:bubble_column[drag_down=true]",
    "minecraft:bubble_column[drag_down=false]",
};

const char *hc_block_name(uint16_t id) {
    return NAMES[id];
}

int32_t hc_block_by_name(const char *name, int32_t len) {
    for (int32_t i = 0; i < HC_B_COUNT; i++)
        if ((int32_t)strlen(NAMES[i]) == len &&
            memcmp(NAMES[i], name, (size_t)len) == 0)
            return i;
    return -1;
}

/* BlockStateBase 캐시 플래그 (26.2 Blocks.<clinit> 등록 체인 재구성 —
 * 9b 신규 패밀리 값은 R1 recon 노트로 확정; 확정 전 임시값은 R1 랜딩 시
 * 이 테이블만 고친다. 기존 57개는 9a 시맨틱 그대로다.)
 *  F_MOTION  blocksMotion()
 *  F_SOLID   isSolid() (legacySolid)
 *  F_FULL    면 폐색 완전 큐브 (occlusion)
 *  F_LEAVES  LeavesBlock (MOTION_BLOCKING_NO_LEAVES 제외 대상)
 *  F_REPL    canBeReplaced()
 *  F_WLOG    waterlogged=true (FluidState = 소스 물) */
enum {
    F_MOTION = 1,
    F_SOLID = 2,
    F_FULL = 4,
    F_LEAVES = 8,
    F_REPL = 16,
    F_WLOG = 32,
};

static const uint8_t FLAGS[HC_B_COUNT] = {
    F_REPL, F_MOTION|F_SOLID|F_FULL, F_REPL, F_REPL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 0, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    /* --- step 9 (9b) --- */
    F_REPL, F_REPL, 0, 0, F_MOTION|F_SOLID|F_FULL, 0, 0, 0, 0, F_REPL, 
    F_REPL, F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_FULL, F_MOTION|F_SOLID|F_FULL, 
    F_MOTION|F_SOLID|F_LEAVES, F_MOTION|F_SOLID|F_LEAVES, 
    F_MOTION|F_SOLID|F_LEAVES, F_MOTION|F_SOLID|F_LEAVES, 
    F_MOTION|F_SOLID|F_LEAVES, F_MOTION|F_SOLID|F_LEAVES, 
    F_MOTION|F_SOLID|F_LEAVES, F_MOTION|F_SOLID|F_LEAVES|F_WLOG, 
    F_MOTION|F_SOLID|F_LEAVES|F_WLOG, F_MOTION|F_SOLID|F_LEAVES|F_WLOG, 
    F_MOTION|F_SOLID|F_LEAVES|F_WLOG, F_MOTION|F_SOLID|F_LEAVES|F_WLOG, 
    F_MOTION|F_SOLID|F_LEAVES|F_WLOG, F_MOTION|F_SOLID|F_LEAVES|F_WLOG, 
    F_MOTION|F_SOLID|F_LEAVES, F_MOTION|F_SOLID|F_LEAVES, 
    F_MOTION|F_SOLID|F_LEAVES, F_MOTION|F_SOLID|F_LEAVES, 
    F_MOTION|F_SOLID|F_LEAVES, F_MOTION|F_SOLID|F_LEAVES, 
    F_MOTION|F_SOLID|F_LEAVES, F_MOTION|F_SOLID|F_LEAVES|F_WLOG, 
    F_MOTION|F_SOLID|F_LEAVES|F_WLOG, F_MOTION|F_SOLID|F_LEAVES|F_WLOG, 
    F_MOTION|F_SOLID|F_LEAVES|F_WLOG, F_MOTION|F_SOLID|F_LEAVES|F_WLOG, 
    F_MOTION|F_SOLID|F_LEAVES|F_WLOG, F_MOTION|F_SOLID|F_LEAVES|F_WLOG, 
    F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, F_MOTION|F_SOLID, F_MOTION|F_SOLID, F_MOTION|F_SOLID, 
    F_MOTION|F_SOLID, F_MOTION|F_SOLID, F_MOTION|F_SOLID, F_MOTION|F_SOLID, 
    F_MOTION|F_SOLID, F_MOTION|F_SOLID, F_MOTION|F_SOLID, F_MOTION|F_SOLID, 
    F_MOTION|F_SOLID, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, F_REPL, F_REPL, F_REPL, F_REPL, 
    F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, 
    F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, 
    F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, 
    F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, 
    F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, 
    F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, 
    F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL|F_WLOG, F_REPL|F_WLOG, 
    F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, 
    F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, 
    F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, 
    F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, 
    F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, 
    F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, 
    F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, 
    F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, 
    F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, 
    F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, 
    F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, 
    F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, 
    F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, 
    F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, 
    F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, F_REPL|F_WLOG, 
    F_REPL|F_WLOG, 0, F_WLOG, 0, F_WLOG, 0, F_WLOG, 0, F_WLOG, 0, F_WLOG, 0, 
    F_WLOG, 0, F_WLOG, 0, F_WLOG, 0, F_WLOG, 0, F_WLOG, 0, F_WLOG, 0, 
    F_WLOG, 0, F_WLOG, 0, F_WLOG, 0, F_WLOG, 0, F_WLOG,
    0, 0, /* mushrooms */
    /* --- Task 10 (26.2 Blocks.<clinit> 등록 체인에서 유도):
     * rooted_dirt/melon/smooth_basalt/amethyst_block/budding_amethyst =
     * 풀 불투명 큐브; hanging_roots/seagrass 계열 = replaceable 식물
     * (seagrass 는 유체가 항상 물 — R4 §5); azalea 잎 = 기존 잎과 동일;
     * amethyst 싹/클러스터 = 충돌 있음(blocksMotion/legacySolid), 부분
     * 형상이라 F_FULL 없음. */
    F_MOTION | F_SOLID | F_FULL,        /* rooted_dirt */
    F_REPL,                             /* hanging_roots */
    F_REPL | F_WLOG,                    /* hanging_roots[wl] */
    F_REPL | F_WLOG,                    /* seagrass */
    F_REPL | F_WLOG,                    /* tall_seagrass lower */
    F_REPL | F_WLOG,                    /* tall_seagrass upper */
    F_MOTION | F_SOLID | F_FULL,        /* melon */
    F_MOTION | F_SOLID | F_FULL,        /* smooth_basalt */
    F_MOTION | F_SOLID | F_FULL,        /* amethyst_block */
    F_MOTION | F_SOLID | F_FULL,        /* budding_amethyst */
    /* azalea_leaves 14 (wl 7+7) */
    F_MOTION | F_SOLID | F_LEAVES, F_MOTION | F_SOLID | F_LEAVES,
    F_MOTION | F_SOLID | F_LEAVES, F_MOTION | F_SOLID | F_LEAVES,
    F_MOTION | F_SOLID | F_LEAVES, F_MOTION | F_SOLID | F_LEAVES,
    F_MOTION | F_SOLID | F_LEAVES,
    F_MOTION | F_SOLID | F_LEAVES | F_WLOG,
    F_MOTION | F_SOLID | F_LEAVES | F_WLOG,
    F_MOTION | F_SOLID | F_LEAVES | F_WLOG,
    F_MOTION | F_SOLID | F_LEAVES | F_WLOG,
    F_MOTION | F_SOLID | F_LEAVES | F_WLOG,
    F_MOTION | F_SOLID | F_LEAVES | F_WLOG,
    F_MOTION | F_SOLID | F_LEAVES | F_WLOG,
    /* flowering_azalea_leaves 14 */
    F_MOTION | F_SOLID | F_LEAVES, F_MOTION | F_SOLID | F_LEAVES,
    F_MOTION | F_SOLID | F_LEAVES, F_MOTION | F_SOLID | F_LEAVES,
    F_MOTION | F_SOLID | F_LEAVES, F_MOTION | F_SOLID | F_LEAVES,
    F_MOTION | F_SOLID | F_LEAVES,
    F_MOTION | F_SOLID | F_LEAVES | F_WLOG,
    F_MOTION | F_SOLID | F_LEAVES | F_WLOG,
    F_MOTION | F_SOLID | F_LEAVES | F_WLOG,
    F_MOTION | F_SOLID | F_LEAVES | F_WLOG,
    F_MOTION | F_SOLID | F_LEAVES | F_WLOG,
    F_MOTION | F_SOLID | F_LEAVES | F_WLOG,
    F_MOTION | F_SOLID | F_LEAVES | F_WLOG,
    /* amethyst 싹/클러스터 48 (size 4 x facing 6 x wl 2) */
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_MOTION | F_SOLID, F_MOTION | F_SOLID | F_WLOG,
    F_REPL, /* cave_air */
    /* monster_room (R5d): cobble/mossy 풀 큐브; spawner 는 noOcclusion
     * (Blocks.<clinit> — 렌더 비고체, 라이트 dampening 0); chest 는 부분
     * 형상 (F_FULL 없음), 월드젠 상태는 wl=false 뿐 */
    F_MOTION | F_SOLID | F_FULL, /* cobblestone */
    F_MOTION | F_SOLID | F_FULL, /* mossy_cobblestone */
    F_MOTION | F_SOLID,          /* spawner */
    F_MOTION | F_SOLID,          /* chest N */
    F_MOTION | F_SOLID,          /* chest S */
    F_MOTION | F_SOLID,          /* chest W */
    F_MOTION | F_SOLID,          /* chest E */
    /* 밴드 링 초목: bush 만 replaceable() (Blocks.<clinit> bc 4441);
     * firefly_bush/sugar_cane/kelp 는 replaceable 없음; kelp 계열은
     * 유체가 항상 물 (F_WLOG = fluid_nonempty); pumpkin 은 평범한 풀 큐브 */
    F_REPL,                      /* bush */
    F_MOTION | F_SOLID | F_FULL, /* pumpkin */
    0,                           /* sugar_cane[age=0] */
    0,                           /* firefly_bush */
    F_WLOG,                      /* kelp[age=20] */
    F_WLOG,                      /* kelp[age=21] */
    F_WLOG,                      /* kelp[age=22] */
    F_WLOG,                      /* kelp[age=23] */
    F_WLOG,                      /* kelp_plant */
    /* water[level=1..15]: 흐르는 물 — replaceable, 유체는 물이지만 소스
     * 아님 (F_WLOG 는 '소스 물' 시맨틱이라 주지 않는다; fluid_nonempty 는
     * 아래 술어에서 레인지로 처리) */
    F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL,
    F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL, F_REPL,
    /* bubble_column: 유체 = 물 소스 (F_WLOG 시맨틱과 일치), replaceable */
    F_REPL | F_WLOG,             /* bubble_column[drag_down=true] */
    F_REPL | F_WLOG,             /* bubble_column[drag_down=false] */
};

int hc_block_is_air(uint16_t id) {
    /* BlockState.isAir — air/cave_air (void_air 는 월드젠에 못 나온다) */
    return id == HC_B_AIR || id == HC_B_CAVE_AIR;
}

int hc_block_is_fluid(uint16_t id) {
    return id == HC_B_WATER || id == HC_B_LAVA;
}

int hc_block_blocks_motion(uint16_t id) {
    return (FLAGS[id] & F_MOTION) != 0;
}

int hc_block_is_solid(uint16_t id) {
    return (FLAGS[id] & F_SOLID) != 0;
}

int hc_block_is_full_cube(uint16_t id) {
    return (FLAGS[id] & F_FULL) != 0;
}

int hc_block_fluid_nonempty(uint16_t id) {
    return id == HC_B_WATER || id == HC_B_LAVA || (FLAGS[id] & F_WLOG) != 0 ||
           (id >= HC_B_WATER_FLOW_BASE && id < HC_B_WATER_FLOW_BASE + 15);
}

int hc_block_fluid_is_water(uint16_t id) {
    return id == HC_B_WATER || (FLAGS[id] & F_WLOG) != 0;
}

int hc_block_is_leaves(uint16_t id) {
    return (FLAGS[id] & F_LEAVES) != 0;
}

int hc_block_is_waterlogged(uint16_t id) {
    return (FLAGS[id] & F_WLOG) != 0;
}

int hc_block_is_replaceable(uint16_t id) {
    return (FLAGS[id] & F_REPL) != 0;
}
